import { FormEvent, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { Menu, Search, ShoppingBag, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger, SheetClose } from "@/components/ui/sheet";
import { useCart } from "@/state/cart";
const nav=["Feminino","Masculino","Casual","Elegante","Tênis","Acessórios"];
export function SiteHeader(){const {count,hydrated}=useCart();const [searchOpen,setSearchOpen]=useState(false);const navigate=useNavigate();function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const q=String(fd.get("q")||"").trim();if(q)void navigate({to:"/catalogo",search:{q}});setSearchOpen(false)}return <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur-sm"><div className="bg-primary px-4 py-2 text-center text-[10px] uppercase text-primary-foreground sm:text-xs">Frete grátis acima de R$ 699 · 3x sem juros</div><div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-4 sm:px-8 lg:h-20 lg:px-12"><div className="lg:hidden"><Sheet><SheetTrigger asChild><Button variant="ghost" size="icon" aria-label="Abrir menu"><Menu/></Button></SheetTrigger><SheetContent side="left" className="w-[88%] bg-background"><SheetHeader><SheetTitle className="font-display text-3xl">LARGO</SheetTitle></SheetHeader><nav className="mt-12 flex flex-col gap-6">{nav.map(item=><SheetClose asChild key={item}><Link to="/catalogo" search={{categoria:item}} className="font-display text-3xl">{item}</Link></SheetClose>)}</nav></SheetContent></Sheet></div><Link to="/" className="font-display text-3xl tracking-wide lg:text-4xl" aria-label="LARGO — Início">LARGO</Link><nav className="hidden items-center gap-6 lg:flex">{nav.map(item=><Link key={item} to="/catalogo" search={{categoria:item}} className="text-xs uppercase transition-opacity hover:opacity-50">{item}</Link>)}</nav><div className="flex items-center gap-1"><Button variant="ghost" size="icon" aria-label="Buscar" onClick={()=>setSearchOpen(v=>!v)}><Search/></Button><Button asChild variant="ghost" size="icon" className="hidden sm:inline-flex" aria-label="Minha conta"><Link to="/conta"><UserRound/></Link></Button><Button asChild variant="ghost" size="icon" className="relative" aria-label={`Carrinho com ${count} itens`}><Link to="/carrinho"><ShoppingBag/>{hydrated&&count>0&&<span className="absolute right-0 top-0 flex size-4 items-center justify-center rounded-full bg-accent text-[9px] text-accent-foreground">{count}</span>}</Link></Button></div></div>{searchOpen&&<form onSubmit={submit} className="border-t border-border bg-background px-5 py-4"><div className="mx-auto flex max-w-2xl"><Input name="q" autoFocus placeholder="O que você procura?" aria-label="Buscar produtos" className="h-11 rounded-none"/><Button variant="editorial">Buscar</Button></div></form>}</header>}
